### ISSUE TITLE
`bugz attach` complains about needing to login

### ISSUE THREAD

**Issue by vapier** [williamh/pybugz#91]
using 72da4116237ae9f8db13967a5f64b7e455e85095 atm

```
$ bugz login
 * Info: Using [gentoo] (https://bugs.gentoo.org/xmlrpc.cgi)
$ bugz attach 562752 screen-4.3.1-r1.log
...
 # Error: Bugzilla error: You must log in before using this part of Gentoo's Bugzilla.
```

**Comment by williamh** [comment]
@vapier:
The login and logout commands are going away because they use tokens, which the Bugzilla authors have stated are deprecated and will be removed in a release after 5.0. [1]

In the next release, you will have to use your username and password or an api key.
All of these can be passed on the bugz command line or configured for the Bugzilla in your ~/.bugzrc.

[1] https://www.bugzilla.org/docs/5.0/en/html/api/Bugzilla/WebService.html#LOGGING_IN

**Comment by vapier** [comment]
the error message should drive people to the relevant docs and drop hints about getting an API key right ?

**Comment by williamh** [comment]
@vapier:
I know I need to output a message, but I'm not thinking that is a good place to put it.
I'll need to let someone know about it if they have a ~/.bugz_token file. They can do one of two things -- configure their user name and password into the .bugzrc settings for that bugzilla or get an api key and configure it into the .bugzrc settings.
